name: Dependabot auto-merge

on:
  pull_request:
    types: [opened, reopened]
    # Only run for Dependabot
    # Use the "github-actions" bot if your repository uses Dependabot version 2.x
    # Use "dependabot[bot]" if your repository uses Dependabot version 1.x
    # You can check this by looking at the author of a Dependabot-created pull request
    author:
      - dependabot[bot]
      - dependabot-preview[bot]

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
    # Checkout the branch
    - name: Checkout
      uses: actions/checkout@v2

    # Merge the pull request
    - name: Merge pull request
      uses: peter-evans/auto-merge@v2.7.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Merge pull request #${{ github.event.pull_request.number }} from Dependabot"
        merge-method: squash
